name: first-action
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo 'Hello'
      - name : Prinf Bye
        run: echo 'Bye'